### PR TITLE
DeterministicScheduler: Implement getDelay for scheduled tasks

### PR DESCRIPTION
**Pull request by stefanbeller**

### CODE REVIEW

**Comment by npryce** [comment]
Any tests?

**Comment by stefanbeller** [comment]
I'll add some tests.

**Comment by npryce** [comment]
thanks!

**Comment by stefanbeller** [comment]
I implemented this as I hoped we could use this for an internal unit test here. When implementing the unit test I realized the behavior between this and the real java.util.concurrent.ScheduledExecutorService
differs. While the real Executer doesn't warn but just returns 0, this throws a new IllegalStateException("Element not found in the delay queue");

After writing the unit tests I found some problems with multithreading, so I dropped the idea of using jmock, but I will run the tests with some custom threads and a bunch of semaphores now. So I am not really keen on fixing this issue now. (Instead of the new Exception just return 0)

**Pull request merged**
