### PR TITLE
Junit5

### PR DESCRIPTION
**Pull request by olibye**

### CODE REVIEW

**Comment by olibye** [comment]
TODO Make a JUnit5ImposterisingSynchronisedMockery.
As projects often have to make this anway

**Comment by olibye** [comment]
com.google.auto.service is only used at compile time that's why it's a provided dependency.
It writes a service loader file that JUnit5 uses to load extensions.

**Comment by olibye** [comment]
All the tests are a lift and drop of those in jmock-juni4

**Comment by sf105** [comment]
That's a shame... Anyway, don't have much to say as I'm out of practice on this loop.

**Pull request merged**
